### ISSUE TITLE
Contact DerAndere1 also known as DerAndere

### ISSUE THREAD

**Issue by DerAndere1** [DerAndere1/contact_DerAndere1#1]
Add a comment here to contact [DerAndere1](https://github.com/DerAndere1), also known as [DerAndere](https://gitlab.com/DerAndere) on gitlab.com. Attach files by dragging & dropping, selecting them, or pasting from the clipboard.

**Comment by dcorcoran** [comment]
Hi DerAndere, Im a molecular biologist/neuroscientist interested in your pipetbot and GGCGen. I'd like to build a robot to use in the lab and to help other biologists with no programming/engineering experience like myself. Could I ask you some questions about all this? I don't know where is best to message you? Many thanks
David

**Comment by DerAndere1** [comment]
I will read and answer here, but the best is to open a new issue at https://gitlab.com/RobotsByDerAndere/CartesianRobotsByDerAndere/GGCGen/issues . There, you can make the issue confidential if you want to exchange private contact info /discuss  discreetly. Best regards,
DerAndere

**Comment by DerAndere1** [comment]
@dcorcoran : One piece of advice I would like to give you right away:
If you want to use and/or improve my designs (soft- or hardware), I would be glad. If you include it in any product or publication, I would be happy if you acknowledge that. Note though that 
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. 
My design is not production-ready and all my software is in development status. The robot has the inherent potential to cause damage, so test everything thoroughly in a manner that is save for humans and material. I certainly did not include bad code willingly but I am a novice, so run my software only if you have backed up all your personal files. You will need some amount of engineering and programming skills to make this working. Especially pipette tip change was never tested in hardware and I am sure that you will have to spend a lot of time to make that work reliably. Weight in costs of time and personal before building a DIY robot. If you need a robot at work or at uni or at work, it is likely much more reasonable to buy a cheap comerial robot: Search online for "open source pipetting robot" or similar and you will get a comercial pipetting robot+software for 6000 €. If you want to use my project as a basis, you will have to have a very good engineering/programmer team to get a production-ready robot+software for that money. Or you have to do the development in your free time.  

I want I will certainly willing to exchange more thoughts.

**Comment by hobiseven** [comment]
@DerAndere1 
Hi, I am willing to turn my Alfawise STM32 board into a 4 axis CNC controler for styrofoam cutter. It means I need to control X,Y and secondary axix U and V. I also need to control wire heat, which can be donethrough fan PWM. 
What is the status of your Marlin branch for 6 axis? Can we get the endsopts working on 4 axis, and get the Gcode addressing 2 supplemental axis please? 
Code I will change is the Marlin 2.0.3 we ported for Alfawise U30.

**Comment by DerAndere1** [comment]
@hobiseven See discussion at https://github.com/DerAndere1/Marlin/issues/1 . One user showed that he could fix my code to move 6 axes (extra axes were much to slow, though). However there is a language barrier, so until now we don't know how to do it. Someone with Vietnamese language skills could maybe help.

**Comment by hobiseven** [comment]
@DerAndere1 the stm32 alfawise code critical commit is that one https://github.com/MarlinFirmware/Marlin/pull/14030
Anything after that works nicely on the board, at least for the basic functions with a4988 drivers. This is earlier than the commit that complicates integration of the 6 axis in Marlin 2.0.x . 

> as soon as you finish your new branch / new comit I can generate a version that will work on my board relatively easily ( hardest part for me will be to make a clean git process!)

**Comment by DerAndere1** [comment]
@hobiseven: Great. I will go the mentioned route then. If you can invite me to collaborate on your fork https://github.com/hobiseven/Marlin I would prefer to add my next code there because that makes it easier to use the github interface and navigate you through the process in case you get stuck.

**Comment by hobiseven** [comment]
@DerAndere1 There is a branch called /origin/September in tpruvot cloned Git, that was stalled about mid september. It compiles fine. I copied the branch to 6_axis_September_base. 
I think from a commit standpoint, it should avoid the problematic ones as I understood. Tell me if this is a good basis. 
I created a copy of 2.0.4.4 branch and tried to rebase, or remove all the commits after a given date, but still not there yet with Git

**Comment by hobiseven** [comment]
@DerAndere1 done! You have the invite and the branch 6 axis September is ready and tested on hw.

**Comment by hobiseven** [comment]
Hi @DerAndere1 
So far, my code is still at End september status. Is it still the same on your side?

**Comment by DerAndere1** [comment]
6 axis code only works with the September base as long as there is no progress with issue https://github.com/DerAndere1/Marlin/issues/7.

**Comment by MohammadSDGHN** [comment]
Hi @DerAndere1
I'm working on a 6 axis cartesian robot and your code is my solution. The problem is that machine is using TMC2130 drivers on SPI and when I set it on configuration.h , code does not compile.
(EXP: #define X_DRIVER_TYPE  TMC2130)
I'm working on it to find out what cause that and add TMC2130 support.Please give me some advice or help to fix it if you can.
and by the way .... Nice job (Y) :)

**Comment by DerAndere1** [comment]
@MohammadSDGHN you forgot to mention which branch you are using.  I hope I fixed your issue in the branch https://github.com/DerAndere1/Marlin/tree/bf2_6axis_dev14 with my recent commits, However that branch probably still suffers from issue  7 of my Marlin branch. Be warned: I expect that many features of special stepper drivers do not yet work with 6 axes. You are one of the first who tries it. It would be great if you could test and give feedback at https://github.com/DerAndere1/Marlin/issues

**Comment by MohammadSDGHN** [comment]
@DerAndere1 
Sorry! mistakenly I was working on bf2_6axis_dev!! I switched to bf2_6axis_dev14 now.
Unfortunately that commit had same problem. I'm willing to help fixing it
1- Is it possible to contact you trough E-mail or something?
2-This error stucked with me. Seems like syntax error but it is not.Any idea where I should look for?
![image](https://user-images.githubusercontent.com/4924021/82056924-ddb54180-96d7-11ea-806c-5c56985c6533.png)

**Comment by DerAndere1** [comment]
That is a tricky one, the mentioned line of code is only loosely related to the actual problem: That compiler error means that some TMC-related code for the axes IJK is not properly surrounded by ´#if NON_E_AXES >3 ... #endif` preprocessor directives. I suspect the config files or file sanitycheck.h . Did you pull the most recent commits from my bf2_6axis_dev14? You can open a new issue at https://github.com/DerAndere1/Marlin/issues and attach your configs as a zip archive to the report if you want me to fix the it. If you need to discuss in descretion, you can create a new issue at https://gitlab.com/contact_derandere/contact_derandere/-/issues : Gitlab allows you to mark issues as confidential so noone else except us can see it. I get email notifications if someone reports an issue.

**Comment by MohammadSDGHN** [comment]
OK .. using -commit [5b5cea8](https://github.com/DerAndere1/Marlin/commit/5b5cea83a6977ff5853dd139bf1f3d85c6db307a)-  and some changes (which I don't remember where it was) now I can compile without errors. I'm trying to customize it. Thanks and please check my version. most of my changes have comment and date.I'll inform you with latest and result. 
[Marlin-bf2_6axis_dev14.zip](https://github.com/DerAndere1/contact_DerAndere1/files/4644793/Marlin-bf2_6axis_dev14.zip)

**Comment by DerAndere1** [comment]
Great that you could make it compile for your machine. I downloaded your zip and will add the changes to my code. Do you mind giving me an update how the machine performs with this firmware? any issues with feedrate on the additional axes I, J or K? If you need more tips, just stay in touch. In case you develop a lab robot, you might also be interested in my control software [pyotronext](https://gitlab.com/RobotsByDerAndere/pyotronext). Regards, DerAndere
