### ISSUE TITLE
7th axis for 5 D printer

### ISSUE THREAD

**Issue by HendrikJan-5D** [DerAndere1/contact_DerAndere1#4]
Hello DerAndere

I am new to this forum.

As a member of   3d.hcc.nl    , a hobby club of members who are involved in 3d printing, 3d scanning, cad software (fusion 360).
I am involved in technical support and new developments in the 3d field.
In the context of this I am building a 5 axis 3d printer.
This can be done by turning and tilting the printhead, or by turning and tilting the bed.

Because I couldn't choose the best method, I decoder to built both in the 3d printer, which results in a 3d printer with 7 axes.

See         https://3d.hcc.nl/126-nieuwe-ontwikkelling-3d-printen-jan-kappers.html

All this is controlled by a BTT GTR V1.0 plus M5 V1.0 board with your custom Marlin-Marlin2ForPipetBot software for 6 axes.
Many thanks for this!

Globally all 6 axes work, however it's still not possible to control the axe for controlling (turning) the axes for the bed.

My question is:  is it possible for you that you add an extra axis to the software?

Marlin-Marlin2ForPipetBot

Kind regards,

Jan Kappers

**Comment by DerAndere1** [comment]
I guess this is fixed. If there is still a problem, open a bug report at https://github.com/DerAndere1/Marlin/issues
