### ISSUE TITLE
What's your more recent branch of 6axis?

### ISSUE THREAD

**Issue by FNeo31** [DerAndere1/contact_DerAndere1#5]
Hello again, I'm sorry for not develop more before but the time is short. 
Now I'm working with my CNC with the 5 axis but with the workaround.
I want to put the 6 axis on the most recent version of the Marlin to try to add the RTCP feature to the machine. Can you say what's your more recent working brunch to try to make the merge on latest version of Marlin?

Thanks 
FNeo31

**Comment by DerAndere1** [comment]
Please refer to the [wiki](https://github.com/DerAndere1/Marlin/wiki) in my Marlin fork to get a general overview of the branches. In addition, you may be interested in one of the open issues in my Marlin fork. In the discussion of the issues I will usually provide a link to the branch in which I try to fix that issue.
